language: java

dist: trusty

cache:
  directories:
  - ~/.m2

matrix:
  include:
    - jdk: oraclejdk8
      env:
        - DESC="verifications"
      script: mvn verify

    - jdk: oraclejdk8
      env:
        - DESC="codecov analysis"
      # skip integration tests
      script: mvn test cobertura:cobertura
      after_success:
        # push report to codecov server
        bash <(curl -s https://codecov.io/bash)

#    - jdk: oraclejdk8
#      env:
#        - DESC="sonarcloud.io analysis"
#      script: mvn test sonar:sonar -Dsonar.projectKey=damianszczepanik_build-history-manager-plugin -Dsonar.organization=damianszczepanik -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
#      if: branch = master
