language: java

cache:
  directories:
    - ~/.m2

git:
  depth: false # remove the --depth to support full git blame by Sonarqube

matrix:
  include:
    - jdk: openjdk8
      env:
        - DESC="tests by jdk8"
      script: mvn verify

    - jdk: oraclejdk11
      env:
        - DESC="tests by oracle11"
      script:
        - mvn clean verify

    - jdk: openjdk11
      env:
        - DESC="tests by openjdk11"
      script:
        - mvn clean verify

    - jdk: oraclejdk11
      env:
        - DESC="static analysis"
      script:
        # execute out of sonar plugin as Sonarcloud does not have access to the repo which I'm not owner of
        # SONAR_TOKEN must be defined
        - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=damianszczepanik -Dsonar.projectKey=damianszczepanik_build-history-manager-plugin

after_success:
  # push report to codecov server
  bash <(curl -s https://codecov.io/bash)
