name: build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    strategy:
      matrix:
        java: [ '17', '21' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt

      # requires by org.jenkins-ci.plugins:plugin:5.x
      # can be deleted when default maven will be upgraded from 3.8.*
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - run: mvn --batch-mode verify
