name: codecov

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      # requires by org.jenkins-ci.plugins:plugin:5.x
      # can be deleted when default maven will be upgraded from 3.8.*
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Generate code coverage
        run: mvn --batch-mode test

      - uses: codecov/codecov-action@v3.1.6
