name: sonarcloud.io

on:
  push:
    branches:
      - master
  # do not validate pull requests because SONAR_TOKEN is available only for project owner

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt

      # requires by org.jenkins-ci.plugins:plugin:5.x
      # can be deleted when default maven will be upgraded from 3.8.*
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Run Sonar scanner
        run: mvn --batch-mode package sonar:sonar -Dsonar.projectKey=damianszczepanik_build-history-manager-plugin -Dsonar.organization=damianszczepanik -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
